### ISSUE TITLE
Issue with the Download and view lab manual button

### ISSUE THREAD

**Issue by asif-khan-2k19** [acetcs/codingClub#13]
In the Latest PR, the view lab manual and download lab manual buttons are working in the localhost and viewing the files and also downloading the files correctly. But After hosting, its download link is getting converted into pdf_name.pdf.html which is not downloading the file and also not showing it.

**Comment by saifrahmn** [comment]
Vitepress considers every file as html, it will make a markdown file as html, or even  a pdf file. So if we want to add a file with its own extension and not html we should add an attribute in link tag i.e target="_self".
`<a href="/pdfs/OS_Lab_manual.pdf"  target="_self">`
**Note: That the pdf file or any file that you want to show should be in public folder inside docs.**
